services:
  signin:
    image: zljiscx/asus-signin:latest
    container_name: asus-signin
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5000:5000"
    restart: unless-stopped
